export type EnWord = { en: string; tr: string };

// A1 — temel kelimeler (renkler, sayılar, aile, hayvanlar, yiyecek, ev, fiiller)
export const ENGLISH_WORDS_EASY: EnWord[] = [
  { en: 'apple', tr: 'elma' },
  { en: 'book', tr: 'kitap' },
  { en: 'cat', tr: 'kedi' },
  { en: 'dog', tr: 'köpek' },
  { en: 'fish', tr: 'balık' },
  { en: 'bird', tr: 'kuş' },
  { en: 'tree', tr: 'ağaç' },
  { en: 'flower', tr: 'çiçek' },
  { en: 'sun', tr: 'güneş' },
  { en: 'moon', tr: 'ay' },
  { en: 'star', tr: 'yıldız' },
  { en: 'water', tr: 'su' },
  { en: 'milk', tr: 'süt' },
  { en: 'bread', tr: 'ekmek' },
  { en: 'egg', tr: 'yumurta' },
  { en: 'cake', tr: 'kek' },
  { en: 'house', tr: 'ev' },
  { en: 'car', tr: 'araba' },
  { en: 'bus', tr: 'otobüs' },
  { en: 'train', tr: 'tren' },
  { en: 'ball', tr: 'top' },
  { en: 'pen', tr: 'kalem' },
  { en: 'bag', tr: 'çanta' },
  { en: 'hat', tr: 'şapka' },
  { en: 'shoe', tr: 'ayakkabı' },
  { en: 'shirt', tr: 'gömlek' },
  { en: 'dress', tr: 'elbise' },
  { en: 'red', tr: 'kırmızı' },
  { en: 'blue', tr: 'mavi' },
  { en: 'green', tr: 'yeşil' },
  { en: 'yellow', tr: 'sarı' },
  { en: 'white', tr: 'beyaz' },
  { en: 'black', tr: 'siyah' },
  { en: 'orange', tr: 'turuncu' },
  { en: 'pink', tr: 'pembe' },
  { en: 'purple', tr: 'mor' },
  { en: 'mother', tr: 'anne' },
  { en: 'father', tr: 'baba' },
  { en: 'sister', tr: 'kız kardeş' },
  { en: 'brother', tr: 'erkek kardeş' },
  { en: 'baby', tr: 'bebek' },
  { en: 'friend', tr: 'arkadaş' },
  { en: 'teacher', tr: 'öğretmen' },
  { en: 'student', tr: 'öğrenci' },
  { en: 'eye', tr: 'göz' },
  { en: 'ear', tr: 'kulak' },
  { en: 'nose', tr: 'burun' },
  { en: 'mouth', tr: 'ağız' },
  { en: 'hand', tr: 'el' },
  { en: 'foot', tr: 'ayak' },
  { en: 'head', tr: 'baş' },
  { en: 'arm', tr: 'kol' },
  { en: 'leg', tr: 'bacak' },
  { en: 'door', tr: 'kapı' },
  { en: 'window', tr: 'pencere' },
  { en: 'table', tr: 'masa' },
  { en: 'chair', tr: 'sandalye' },
  { en: 'bed', tr: 'yatak' },
  { en: 'big', tr: 'büyük' },
  { en: 'small', tr: 'küçük' },
  { en: 'hot', tr: 'sıcak' },
  { en: 'cold', tr: 'soğuk' },
  { en: 'good', tr: 'iyi' },
  { en: 'bad', tr: 'kötü' },
  { en: 'new', tr: 'yeni' },
  { en: 'old', tr: 'eski' },
  { en: 'happy', tr: 'mutlu' },
  { en: 'sad', tr: 'üzgün' },
  { en: 'run', tr: 'koşmak' },
  { en: 'walk', tr: 'yürümek' },
  { en: 'eat', tr: 'yemek' },
  { en: 'drink', tr: 'içmek' },
  { en: 'sleep', tr: 'uyumak' },
  { en: 'play', tr: 'oynamak' },
  { en: 'read', tr: 'okumak' },
  { en: 'write', tr: 'yazmak' },
  { en: 'open', tr: 'açmak' },
  { en: 'close', tr: 'kapatmak' },
  { en: 'one', tr: 'bir' },
  { en: 'two', tr: 'iki' },
  { en: 'three', tr: 'üç' },
  { en: 'four', tr: 'dört' },
  { en: 'five', tr: 'beş' },
  { en: 'six', tr: 'altı' },
  { en: 'seven', tr: 'yedi' },
  { en: 'eight', tr: 'sekiz' },
  { en: 'nine', tr: 'dokuz' },
  { en: 'ten', tr: 'on' },
  { en: 'horse', tr: 'at' },
  { en: 'cow', tr: 'inek' },
  { en: 'sheep', tr: 'koyun' },
  { en: 'rabbit', tr: 'tavşan' },
  { en: 'duck', tr: 'ördek' },
  { en: 'lion', tr: 'aslan' },
  { en: 'elephant', tr: 'fil' },
  { en: 'bear', tr: 'ayı' },
  { en: 'frog', tr: 'kurbağa' },
  { en: 'butterfly', tr: 'kelebek' },
];

// A2–B1 — orta düzey kelimeler (fiiller, sıfatlar, yer, zaman, aktiviteler)
export const ENGLISH_WORDS_MEDIUM: EnWord[] = [
  { en: 'beautiful', tr: 'güzel' },
  { en: 'important', tr: 'önemli' },
  { en: 'understand', tr: 'anlamak' },
  { en: 'question', tr: 'soru' },
  { en: 'answer', tr: 'cevap' },
  { en: 'morning', tr: 'sabah' },
  { en: 'evening', tr: 'akşam' },
  { en: 'always', tr: 'her zaman' },
  { en: 'never', tr: 'asla' },
  { en: 'sometimes', tr: 'bazen' },
  { en: 'kitchen', tr: 'mutfak' },
  { en: 'bedroom', tr: 'yatak odası' },
  { en: 'bathroom', tr: 'banyo' },
  { en: 'garden', tr: 'bahçe' },
  { en: 'country', tr: 'ülke' },
  { en: 'language', tr: 'dil' },
  { en: 'family', tr: 'aile' },
  { en: 'together', tr: 'birlikte' },
  { en: 'different', tr: 'farklı' },
  { en: 'animal', tr: 'hayvan' },
  { en: 'weather', tr: 'hava' },
  { en: 'summer', tr: 'yaz' },
  { en: 'winter', tr: 'kış' },
  { en: 'spring', tr: 'ilkbahar' },
  { en: 'autumn', tr: 'sonbahar' },
  { en: 'hungry', tr: 'aç' },
  { en: 'thirsty', tr: 'susuz' },
  { en: 'dream', tr: 'rüya' },
  { en: 'learn', tr: 'öğrenmek' },
  { en: 'listen', tr: 'dinlemek' },
  { en: 'speak', tr: 'konuşmak' },
  { en: 'think', tr: 'düşünmek' },
  { en: 'know', tr: 'bilmek' },
  { en: 'love', tr: 'sevmek' },
  { en: 'help', tr: 'yardım etmek' },
  { en: 'find', tr: 'bulmak' },
  { en: 'want', tr: 'istemek' },
  { en: 'make', tr: 'yapmak' },
  { en: 'show', tr: 'göstermek' },
  { en: 'start', tr: 'başlamak' },
  { en: 'stop', tr: 'durmak' },
  { en: 'buy', tr: 'satın almak' },
  { en: 'cook', tr: 'pişirmek' },
  { en: 'clean', tr: 'temizlemek' },
  { en: 'wash', tr: 'yıkamak' },
  { en: 'hospital', tr: 'hastane' },
  { en: 'market', tr: 'pazar' },
  { en: 'travel', tr: 'seyahat' },
  { en: 'enjoy', tr: 'zevk almak' },
  { en: 'believe', tr: 'inanmak' },
  { en: 'mountain', tr: 'dağ' },
  { en: 'river', tr: 'nehir' },
  { en: 'ocean', tr: 'okyanus' },
  { en: 'forest', tr: 'orman' },
  { en: 'cloud', tr: 'bulut' },
  { en: 'rain', tr: 'yağmur' },
  { en: 'snow', tr: 'kar' },
  { en: 'wind', tr: 'rüzgar' },
  { en: 'fire', tr: 'ateş' },
  { en: 'money', tr: 'para' },
  { en: 'phone', tr: 'telefon' },
  { en: 'computer', tr: 'bilgisayar' },
  { en: 'music', tr: 'müzik' },
  { en: 'dance', tr: 'dans' },
  { en: 'sport', tr: 'spor' },
  { en: 'color', tr: 'renk' },
  { en: 'picture', tr: 'resim' },
  { en: 'story', tr: 'hikaye' },
  { en: 'number', tr: 'sayı' },
  { en: 'lesson', tr: 'ders' },
  { en: 'holiday', tr: 'tatil' },
  { en: 'birthday', tr: 'doğum günü' },
  { en: 'present', tr: 'hediye' },
  { en: 'party', tr: 'parti' },
  { en: 'healthy', tr: 'sağlıklı' },
  { en: 'strong', tr: 'güçlü' },
  { en: 'brave', tr: 'cesur' },
  { en: 'clever', tr: 'akıllı' },
  { en: 'funny', tr: 'komik' },
  { en: 'quiet', tr: 'sessiz' },
  { en: 'loud', tr: 'gürültülü' },
  { en: 'fast', tr: 'hızlı' },
  { en: 'slow', tr: 'yavaş' },
  { en: 'early', tr: 'erken' },
  { en: 'late', tr: 'geç' },
  { en: 'right', tr: 'doğru' },
  { en: 'wrong', tr: 'yanlış' },
  { en: 'easy', tr: 'kolay' },
  { en: 'hard', tr: 'zor' },
  { en: 'dark', tr: 'karanlık' },
  { en: 'light', tr: 'aydınlık' },
  { en: 'clean', tr: 'temiz' },
  { en: 'dirty', tr: 'kirli' },
  { en: 'empty', tr: 'boş' },
  { en: 'full', tr: 'dolu' },
  { en: 'free', tr: 'özgür' },
  { en: 'busy', tr: 'meşgul' },
  { en: 'ready', tr: 'hazır' },
  { en: 'sorry', tr: 'özür dilerim' },
];

// B1–B2 — ileri düzey kelimeler (soyut kavramlar, uzun kelimeler)
export const ENGLISH_WORDS_HARD: EnWord[] = [
  { en: 'environment', tr: 'çevre' },
  { en: 'opportunity', tr: 'fırsat' },
  { en: 'responsibility', tr: 'sorumluluk' },
  { en: 'achievement', tr: 'başarı' },
  { en: 'experience', tr: 'deneyim' },
  { en: 'necessary', tr: 'gerekli' },
  { en: 'education', tr: 'eğitim' },
  { en: 'development', tr: 'gelişme' },
  { en: 'technology', tr: 'teknoloji' },
  { en: 'community', tr: 'topluluk' },
  { en: 'organization', tr: 'organizasyon' },
  { en: 'international', tr: 'uluslararası' },
  { en: 'relationship', tr: 'ilişki' },
  { en: 'information', tr: 'bilgi' },
  { en: 'independent', tr: 'bağımsız' },
  { en: 'traditional', tr: 'geleneksel' },
  { en: 'celebration', tr: 'kutlama' },
  { en: 'dangerous', tr: 'tehlikeli' },
  { en: 'interesting', tr: 'ilginç' },
  { en: 'successful', tr: 'başarılı' },
  { en: 'comfortable', tr: 'rahat' },
  { en: 'wonderful', tr: 'harika' },
  { en: 'knowledge', tr: 'bilgi' },
  { en: 'population', tr: 'nüfus' },
  { en: 'university', tr: 'üniversite' },
  { en: 'professional', tr: 'profesyonel' },
  { en: 'electricity', tr: 'elektrik' },
  { en: 'transportation', tr: 'ulaşım' },
  { en: 'competition', tr: 'yarışma' },
  { en: 'imagination', tr: 'hayal gücü' },
  { en: 'conversation', tr: 'konuşma' },
  { en: 'satisfaction', tr: 'memnuniyet' },
  { en: 'preparation', tr: 'hazırlık' },
  { en: 'suggestion', tr: 'öneri' },
  { en: 'presentation', tr: 'sunum' },
  { en: 'entertainment', tr: 'eğlence' },
  { en: 'approximately', tr: 'yaklaşık olarak' },
  { en: 'unfortunately', tr: 'maalesef' },
  { en: 'immediately', tr: 'hemen' },
  { en: 'significantly', tr: 'önemli ölçüde' },
  { en: 'particularly', tr: 'özellikle' },
  { en: 'measurement', tr: 'ölçüm' },
  { en: 'temperature', tr: 'sıcaklık' },
  { en: 'management', tr: 'yönetim' },
  { en: 'recommend', tr: 'tavsiye etmek' },
  { en: 'concentrate', tr: 'konsantre olmak' },
  { en: 'appreciate', tr: 'takdir etmek' },
  { en: 'investigate', tr: 'araştırmak' },
  { en: 'participate', tr: 'katılmak' },
  { en: 'demonstrate', tr: 'göstermek' },
  { en: 'disappear', tr: 'kaybolmak' },
  { en: 'difference', tr: 'fark' },
  { en: 'influence', tr: 'etki' },
  { en: 'confidence', tr: 'güven' },
  { en: 'patience', tr: 'sabır' },
  { en: 'adventure', tr: 'macera' },
  { en: 'communicate', tr: 'iletişim kurmak' },
  { en: 'geography', tr: 'coğrafya' },
  { en: 'chemistry', tr: 'kimya' },
  { en: 'mathematics', tr: 'matematik' },
  { en: 'philosophy', tr: 'felsefe' },
  { en: 'psychology', tr: 'psikoloji' },
  { en: 'electricity', tr: 'elektrik' },
  { en: 'government', tr: 'hükümet' },
  { en: 'democracy', tr: 'demokrasi' },
  { en: 'revolution', tr: 'devrim' },
  { en: 'civilization', tr: 'uygarlık' },
  { en: 'atmosphere', tr: 'atmosfer' },
  { en: 'permission', tr: 'izin' },
  { en: 'description', tr: 'tanımlama' },
  { en: 'solution', tr: 'çözüm' },
  { en: 'pollution', tr: 'kirlilik' },
  { en: 'protection', tr: 'koruma' },
  { en: 'direction', tr: 'yön' },
  { en: 'generation', tr: 'nesil' },
  { en: 'observation', tr: 'gözlem' },
  { en: 'imagination', tr: 'hayal gücü' },
  { en: 'extraordinary', tr: 'olağanüstü' },
  { en: 'responsible', tr: 'sorumlu' },
  { en: 'communicate', tr: 'iletişim kurmak' },
  { en: 'encourage', tr: 'teşvik etmek' },
  { en: 'disappoint', tr: 'hayal kırıklığı yaratmak' },
  { en: 'celebrate', tr: 'kutlamak' },
  { en: 'recognize', tr: 'tanımak' },
  { en: 'volunteer', tr: 'gönüllü' },
  { en: 'challenge', tr: 'meydan okumak' },
  { en: 'emergency', tr: 'acil durum' },
  { en: 'consequence', tr: 'sonuç' },
  { en: 'appreciate', tr: 'takdir etmek' },
  { en: 'guarantee', tr: 'garanti' },
  { en: 'laboratory', tr: 'laboratuvar' },
  { en: 'documentary', tr: 'belgesel' },
  { en: 'scholarship', tr: 'burs' },
  { en: 'curiosity', tr: 'merak' },
  { en: 'creativity', tr: 'yaratıcılık' },
  { en: 'ambition', tr: 'hırs' },
  { en: 'determination', tr: 'kararlılık' },
  { en: 'perseverance', tr: 'azim' },
];

export function getEnglishWordsByDifficulty(d: 'easy' | 'medium' | 'hard'): EnWord[] {
  if (d === 'easy') return ENGLISH_WORDS_EASY;
  if (d === 'medium') return ENGLISH_WORDS_MEDIUM;
  return ENGLISH_WORDS_HARD;
}

/** Normalize a spoken string for loose matching */
export function normalizeForMatch(s: string): string {
  return s
    .toLowerCase()
    .trim()
    .replace(/[.,!?;:'"()-]/g, '')
    // Turkish diacritics → latin equivalents (for tr-TR recognition fallback)
    .replace(/ğ/g, 'g')
    .replace(/ı/g, 'i')
    .replace(/ş/g, 's')
    .replace(/ç/g, 'c')
    .replace(/ö/g, 'o')
    .replace(/ü/g, 'u');
}
